FROM i386/ubuntu:14.04

RUN apt-get update && apt-get install -y \
        build-essential

RUN apt-get update && apt-get install -y \
	wine1.6-dev

RUN apt-get update && apt-get install -y \
	libjack-jackd2-dev

RUN apt-cache search libjack
